name: Build releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build ${{ matrix.tag }} Version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["centos:7"]

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setting up the environment
      run: |
        yum makecache
        yum install -y centos-release-scl-rh centos-release-scl
        yum install -y devtoolset-10-gcc devtoolset-10-gcc-c++ devtoolset-10-make wget make python3

    - name: Set node version
      run: |
        source ./node_version
        echo "$LTS_VERSION"
        echo "VERSION=$LTS_VERSION" >> "$GITHUB_ENV"

    - name: Download node source code
      run: |
        echo "https://nodejs.org/dist/v${{ env.VERSION }}/node-v${{ env.VERSION }}.tar.xz"
        wget https://nodejs.org/dist/v${{ env.VERSION }}/node-v${{ env.VERSION }}.tar.xz
        tar -Jxf node-v${{ env.VERSION }}.tar.xz

    - name: Build node
      run: |
        source /opt/rh/devtoolset-10/enable
        cd node-v${{ env.VERSION }}
        ./configure --prefix=../node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT)
        make -j$(($(nproc --all)+1)) && make install && cp -a ./{LICENSE,CHANGELOG.md,README.md} ../node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT)/
        strip ../node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT)/bin/node

    - name: Create archive
      run: |
        mkdir tar
        tar Jcvf tar/node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT).tar.xz node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT)
        tar zcvf tar/node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT).tar.gz node-v${{ env.VERSION }}-linux-x$(getconf LONG_BIT)
        cd tar && sha256sum node-v* > sha256sum.txt

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        path: tar/*